spring.datasource.url=jdbc:postgresql://dpg-d6olgev5r7bs73e87ru0-a.singapore-postgres.render.com:5432/moneymanager_d437?sslmode=require
spring.datasource.username=moneymanager_d437_user
spring.datasource.password=qK2wu7b9LlPXNrwYxGfUCApW9gehlkwQ
spring.datasource.driver-class-name=org.postgresql.Driver